import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./_components/sidbar";

const inter = Inter({
  subsets: ["latin"],
  display: "auto",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <div className="flex gap-8 h-full w-full">
          <Sidebar />
          {children}
        </div>
        </body>
    </html>
  );
}
